### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tcyrus**
Changed PNG Badges to SVG

### CODE REVIEW

**Comment by tcyrus** [comment]
Just wanted to check the status of this

**Comment by henryoswald** [comment]
Hey, thanks for this. Can you tell me the benefit of using svg here please?

**Comment by tcyrus** [comment]
@henryoswald SVG's are vectors, so they scale when zooming in the browser or viewing on a retina screen

**Comment by bean5** [comment]
+1

**Comment by henryoswald** [comment]
thanks, done with https://github.com/sharelatex/sharelatex/commit/248d3c5128832fdf46f4249aeaf02a67ccde3687

**Pull request closed without merging**
