### PR TITLE
Added grunt install to install-services script

### PR DESCRIPTION
**Pull request by punkt2**
grunt install needs to run for each service

### CODE REVIEW

**Comment by hfaulds** [comment]
@punkt2 
Hello, sorry I missed your comment on the other PR. I will confess I removed the `grunt install` command accidentally. I did however test this script by removing all of the subfolders, running `grunt install` and then sourcing this script and everything appeared to work. What appears to be broken without this?

**Comment by punkt2** [comment]
As I understand the grunt install in the parent directory only clones the service repositories. To compile the coffeescript files into JavaScript you need to run grunt install within the service directory. But I will try this out again to be sure.

**Comment by punkt2** [comment]
I tried it again and the javascript files are generated with your script. Don't know what the problem was before.

**Comment by iselcuk** [comment]
@hfaulds What is the fastest way to edit coffee files and is it possible to update container just using `grunt install `without building a new image?
I also tried `docker cp` but didn't work for coffee files. (I know I have to compile it first but I got an empty login page after removing the web service and running grunt install)

**Comment by ShaneKilkelly** [comment]
@iselcuk If you're editing the coffeescript/javascript files in a running container, then you'd need to run `sv restart web-sharelatex` in the container afterward for the changes to be picked up.

I'd recommend instead creating a new image with `FROM sharelatex/sharelatex`, and then adding the appropriate files that way.

**Comment by iselcuk** [comment]
@ShaneKilkelly 
I tried to trigger an alert via download button to test it. But there is no response. Is it because my syntax is wrong? 

Edited Pug file: #[https://github.com/iselcuk/web-sharelatex/commit/ec8cd2675199421d5deaa5048d52922b4ab93b54](url)
Edited Coffee file: [https://github.com/iselcuk/web-sharelatex/commit/893b1f4d3b524cb24396f5fa33a6915597558e4d#diff-b3462fe585c09e059ca324e876d9909a](url)

**Comment by iselcuk** [comment]
@ShaneKilkelly 
I tried to trigger an alert via download button to test it. But there is no response. Is it because my syntax is wrong? 

Edited Pug file: [https://github.com/iselcuk/web-sharelatex/commit/ec8cd2675199421d5deaa5048d52922b4ab93b54](url)

Edited Coffee file: [https://github.com/iselcuk/web-sharelatex/commit/893b1f4d3b524cb24396f5fa33a6915597558e4d#diff-b3462fe585c09e059ca324e876d9909a](url)

**Comment by iselcuk** [comment]
@ShaneKilkelly I tried to trigger an alert via download button to test it. But there is no response. Is it because my syntax is wrong?

 [Edited Pug](https://github.com/iselcuk/web-sharelatex/commit/ec8cd2675199421d5deaa5048d52922b4ab93b54)

[Edited Coffee](https://github.com/iselcuk/web-sharelatex/commit/893b1f4d3b524cb24396f5fa33a6915597558e4d#diff-b3462fe585c09e059ca324e876d9909a)

**Comment by ShaneKilkelly** [comment]
@iselcuk the `require 'alert-node'` at the top is probably not going to work, as that code doesn't execute in a node-js process. In this context the usual browser `alert` function should just be available.

**Comment by iselcuk** [comment]
@ShaneKilkelly Unfortunately it didn't work either

**Comment by jdleesmiller** [comment]
@iselcuk At present, there is no officially supported way of doing that. Rebuilding the container is the simplest (albeit slowest) solution. We are hoping to improve this in the future.

**Pull request closed without merging**
